const data = {
    users: [
        {
            name: "Azim Uddin",
            email: "mohammadazimuddin274@gmail.com",
            password: "Azim12@",
            phone: "01883061967",
            address: "Feni, Bangladesh",
        },
        {
            name: "Anisul Islam",
            email: "anisulislam2010@gmail.com",
            password: "Azim12@",
            phone: "04055566",
            address: "Sylhet, Bangladesh",
        },
        {
            name: "Ayman Sadiq",
            email: "aymansadiq@gmail.com",
            password: "Azim12@",
            phone: "04055577",
            address: "Dhaka, Bangladesh",
        },
        {
            name: "Jhankar mahbub",
            email: "jhankarmahbub011@gmail.com",
            password: "Azim12@",
            phone: "04055588",
            address: "USA",
        },
    ],
    products: [
        {
            name: "iPhone 13 mini",
            slug: "iPhone-13-mini",
            description: "The iPhone 13, Apple's latest technological marvel, redefines innovation with its cutting-edge features and sleek design. Building upon its predecessor, the iPhone 13 boasts an array of enhancements, including an advanced A15 Bionic chip for lightning-fast performance, stunning camera upgrades for unparalleled photography, and a vibrant Super Retina XDR display. With its seamless integration of hardware and software, the iPhone 13 sets a new benchmark for the future of smartphones.",
            image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-mini.jpg",
            price: 1000,
            brand: "Apple",
            quantity: 80,
            sold: 20,
            shipping: 0,
            category: "667904cc564d648d0148e491"
        },
        {
            name: "Watch Edition Series 7",
            slug: "watch-edition-series-7",
            description: "Watch 3 Pro is the latest edition of their classic watch series. A bunch of extraordinary features such as a health monitor, and sports mode is combined with the elegant design. Moreover, the latest OS makes it a substitute of your phone and make it easier than ever.",
            image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series-7-titanium.jpg",
            price: 300,
            brand: "Apple",
            quantity: 50,
            sold: 30,
            shipping: 0,
            category: "667b947cb5d450c7b1349cdd"
        },
        {
            name: "iPhone 13 Pro",
            slug: "iPhone-13-pro",
            description: "The iPhone 13, Apple's latest technological marvel, redefines innovation with its cutting-edge features and sleek design. Building upon its predecessor, the iPhone 13 boasts an array of enhancements, including an advanced A15 Bionic chip for lightning-fast performance, stunning camera upgrades for unparalleled photography, and a vibrant Super Retina XDR display. With its seamless integration of hardware and software, the iPhone 13 sets a new benchmark for the future of smartphones.",
            image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg",
            price: 950,
            brand: "Apple",
            quantity: 24,
            sold: 18,
            shipping: 0,
            category: "667904cc564d648d0148e491"
        },
        {
            name: "Hp Envy x360 14-es1023dx Intel Core 7",
            slug: "hp-envy-x360-14-es1023dx-intel-core-7",
            description: "The HP Envy x360 14-es1023dx is the new sensation of the latest-gen laptop category. It is a powerhouse of style and performance. Running on Windows 11, it offers a fresh perspective with a rejuvenated Start menu and advanced connectivity options. Equipped with an Intel Core i7 processor, it ensures exceptional multitasking, stunning graphics, and reliable connectivity. ",
            image: "https://adminapi.applegadgetsbd.com/storage/media/large/Hp-Envy-x360-14-es1023dx-(2024)-a-6424.jpg",
            price: 2000,
            brand: "HP",
            quantity: 18,
            sold: 6,
            shipping: 0,
            category: "667b93eeb5d450c7b1349cdb"
        },
        {
            name: "Watch GT 3",
            slug: "watch-gt-3",
            description: "Watch 3 Pro is the latest edition of their classic watch series. A bunch of extraordinary features such as a health monitor, and sports mode is combined with the elegant design. Moreover, the latest OS makes it a substitute of your phone and make it easier than ever.",
            image: "https://fdn2.gsmarena.com/vv/bigpic/huawei-watch-gt3-new.jpg",
            price: 200,
            brand: "Huawei",
            quantity: 40,
            sold: 26,
            shipping: 0,
            category: "667b947cb5d450c7b1349cdd"
        },
        {
            name: "HP Pavilion 14 DV2005TX Core i7",
            slug: "hp-pavilion-14-dv2005tx-core i7",
            description: "The HP Envy x360 14-es1023dx is the new sensation of the latest-gen laptop category. It is a powerhouse of style and performance. Running on Windows 11, it offers a fresh perspective with a rejuvenated Start menu and advanced connectivity options. Equipped with an Intel Core i7 processor, it ensures exceptional multitasking, stunning graphics, and reliable connectivity.",
            image: "https://adminapi.applegadgetsbd.com/storage/media/large/HP-Pavilion-14-DV2005TX-Pink-9709.jpg",
            price: 1200,
            brand: "HP",
            quantity: 30,
            sold: 22,
            shipping: 0,
            category: "667b93eeb5d450c7b1349cdb"
        },
        {
            name: "iPhone 12 mini",
            slug: "iPhone-12-mini",
            description: "The iPhone 13, Apple's latest technological marvel, redefines innovation with its cutting-edge features and sleek design. Building upon its predecessor, the iPhone 13 boasts an array of enhancements, including an advanced A15 Bionic chip for lightning-fast performance, stunning camera upgrades for unparalleled photography, and a vibrant Super Retina XDR display. With its seamless integration of hardware and software, the iPhone 13 sets a new benchmark for the future of smartphones.",
            image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-mini.jpg",
            price: 770,
            brand: "Apple",
            quantity: 12,
            sold: 27,
            shipping: 0,
            category: "667904cc564d648d0148e491"
        },
        {
            name: "Dell Inspiron 15 3511 Core i3",
            slug: "dell-inspiron-15-3511-core-i3",
            description: "The Dell Inspiron 15 3511, powered by the 11th Generation Intel Core i3 processor and complemented by Intel UHD Graphics, represents a compelling blend of performance and visuals. Designed to meet the demands of modern computing, this laptop offers a seamless experience for both work and play.",
            image: "https://adminapi.applegadgetsbd.com/storage/media/large/Inspiron-15-3511-2922.jpg",
            price: 1500,
            brand: "Dell",
            quantity: 16,
            sold: 5,
            shipping: 0,
            category: "667b93eeb5d450c7b1349cdb"
        },
        {
            name: "Dell 15 3500 Core i5 11th Generation",
            slug: "dell-15-3500-core-i5-11th-generation",
            description: "The Dell Inspiron 15 3511, powered by the 11th Generation Intel Core i3 processor and complemented by Intel UHD Graphics, represents a compelling blend of performance and visuals. Designed to meet the demands of modern computing, this laptop offers a seamless experience for both work and play.",
            image: "https://adminapi.applegadgetsbd.com/storage/media/large/Vostro-15-3500-b-6508.jpg",
            price: 1600,
            brand: "Dell",
            quantity: 50,
            sold: 29,
            shipping: 0,
            category: "667b93eeb5d450c7b1349cdb"
        },
        {
            name: "Galaxy S22 5G",
            slug: "galaxy-s22-5g",
            description: "The galaxy 13, Apple's latest technological marvel, redefines innovation with its cutting-edge features and sleek design. Building upon its predecessor, the galaxy 13 boasts an array of enhancements, including an advanced A15 Bionic chip for lightning-fast performance, stunning camera upgrades for unparalleled photography, and a vibrant Super Retina XDR display. With its seamless integration of hardware and software, the galaxy 13 sets a new benchmark for the future of smartphones.",
            image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-5g.jpg",
            price: 800,
            brand: "Samsung",
            quantity: 20,
            sold: 14,
            shipping: 0,
            category: "667904cc564d648d0148e491"
        },
        {
            name: "ASUS VivoBook 15 X1504ZA 12th Gen Intel Core i7-1255U",
            slug: "asus-vivo-book-15-x1504za-12th-gen-intel-core-i7-1255u",
            description: "The ASUS Inspiron 15 3511, powered by the 11th Generation Intel Core i3 processor and complemented by Intel UHD Graphics, represents a compelling blend of performance and visuals. Designed to meet the demands of modern computing, this laptop offers a seamless experience for both work and play.",
            image: "https://adminapi.applegadgetsbd.com/storage/media/large/ASUS-VivoBook-15-A1504ZA-b-6633.jpg",
            price: 1000,
            brand: "ASUS VivoBook",
            quantity: 10,
            sold: 6,
            shipping: 0,
            category: "667b93eeb5d450c7b1349cdb"
        },
        {
            name: "Galaxy M32 5G",
            slug: "galaxy-m32-5g",
            description: "The galaxy 13, Apple's latest technological marvel, redefines innovation with its cutting-edge features and sleek design. Building upon its predecessor, the galaxy 13 boasts an array of enhancements, including an advanced A15 Bionic chip for lightning-fast performance, stunning camera upgrades for unparalleled photography, and a vibrant Super Retina XDR display. With its seamless integration of hardware and software, the galaxy 13 sets a new benchmark for the future of smartphones.",
            image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m32-5g-new.jpg",
            price: 500,
            brand: "Samsung",
            quantity: 12,
            sold: 8,
            shipping: 0,
            category: "667904cc564d648d0148e491"
        },
    ],
};

module.exports = data;